services:
  - type: web
    name: minio-server
    healthCheckPath: /minio/health/live
    runtime: image
    image: 
      url: docker.io/minio/minio:latest
    dockerCommand: minio server /tmp/data --address $HOST:$PORT --console-address $HOST:$CONSOLE_PORT
    autoDeploy: false
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: 9000
      - key: CONSOLE_PORT
        value: 9090

  - type: web
    name: minio-console
    runtime: docker
    dockerContext: /
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MINIO_HOST
        value: "minio-server"  # Changed this to use just the service name
      - key: MINIO_CONSOLE_PORT
        value: "9090"  # Explicitly set the console port
