services:
  - type: web
    name: minio
    healthCheckPath: /minio/health/live
    runtime: image
    image:
      url: docker.io/minio/minio:latest
    dockerCommand: server /tmp/data --address :$PORT --console-address :$CONSOLE_PORT
    autoDeploy: false
    plan: free
    ports:
      - port: 9000
        protocol: tcp
      - port: 9001
        protocol: tcp
    envVars:
      - key: MINIO_ROOT_USER
        value: mino
      - key: MINIO_ROOT_PASSWORD
        value: minio123
      - key: PORT
        value: 9000
      - key: CONSOLE_PORT
        value: 9001
